<?php

declare(strict_types=1);

require_once __DIR__ . '/lib/auth.php';
require_once __DIR__ . '/lib/projects.php';

station_require_owner();

header('Content-Type: text/plain; charset=utf-8');
echo "# Generated by Station (owner only)\n";
echo "# Route project URLs through Station so access control applies and relative assets still load.\n\n";
echo station_nginx_project_route_snippet() . "\n";
