<?php

declare(strict_types=1);

require_once __DIR__ . '/lib/auth.php';
require_once __DIR__ . '/lib/projects.php';

station_require_owner();

$projects = station_list_projects();
$publicProjects = [];
foreach ($projects as $project) {
    $slug = (string) ($project['slug'] ?? '');
    $visibility = (string) ($project['visibility'] ?? 'private');
    if ($slug !== '' && $visibility === 'public') {
        $publicProjects[] = $slug;
    }
}

header('Content-Type: text/plain; charset=utf-8');

echo "# Generated by Station (owner only)\n";
echo "# Include this in your nginx server block to bypass basic auth only for public projects.\n\n";
echo "# 1) Put this map in http{} scope (not inside server{}):\n";
echo "map \$uri \$secure_project_public {\n";
echo "    default 0;\n";
foreach ($publicProjects as $slug) {
    $safe = preg_replace('/[^a-z0-9\-_]/', '', $slug) ?? '';
    if ($safe === '') {
        continue;
    }
    echo '    ~^/secure/' . $safe . '(/|$) 1;' . "\n";
}
echo "}\n\n";
echo "# 2) In your /secure location, use:\n";
echo "# if (\$secure_project_public = 1) { auth_basic off; }\n";
echo "# else keep auth_basic on;\n";
